### PR TITLE
Improve legal string shown in dashboard terminal view

### PR DESCRIPTION
**Pull request by Dav-Git**
I have edited the legal disclaimer visible in the terminal view to be a little clearer to the end user.

Sadly I couldn't test the allignment yet.

### CODE REVIEW

**Comment by NeuroAssassin** [comment]
Heya @Dav-Git, mind fixing conflicts on this?

**Comment by Dav-Git** [comment]
grafik
I'm just... wow... GitHub... you did a great job...

**Comment by Dav-Git** [comment]
For some reason it's not letting me resolve confilcts... any idea why?

**Comment by NeuroAssassin** [comment]
Can you resolve on a device then push?

**Comment by Dav-Git** [comment]
I done fixed it

**Comment by Dav-Git** [comment]
NEUROOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by NeuroAssassin** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES

**Comment by Dav-Git** [comment]
MERGE

**Pull request closed without merging**
